sudo: required

language: node_js

node_js:
  - "4"

env:
  matrix:
    - FACTORIO_VERSION=0.14.20

before_install:
  - export PANEL_VERSION=$(node -e 'console.log(require("./package").version)')

script:
  - npm test
